chore: switch to zsh

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -9,26 +9,31 @@ set -eu
 # Install Homebrew and packages first
 source "$HOME/.config/yadm/brew.sh"
 
+# Switch to zsh
+if [[ "$SHELL" != *"zsh" ]]; then
+	chsh -s $(which zsh)
+fi
+
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-  echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-  exit 1
+	echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+	exit 1
 fi
 
 declare -a bootstraps
 while IFS= read -r bootstrap; do
-  if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ ~$ ]]; then
-    bootstraps+=("$bootstrap")
-  fi
+	if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ ~$ ]]; then
+		bootstraps+=("$bootstrap")
+	fi
 done < <(find -L "$BOOTSTRAP_D" -type f | sort)
 
 for bootstrap in "${bootstraps[@]}"; do
-  if ! "$bootstrap"; then
-    echo "Error: bootstrap '$bootstrap' failed" >&2
-    exit 1
-  fi
+	if ! "$bootstrap"; then
+		echo "Error: bootstrap '$bootstrap' failed" >&2
+		exit 1
+	fi
 done
 
 echo "Finished processing bootstrap scripts ✅"
